ARG SPARK_IMAGE_TAG=3.3.0-hadoop3.3
FROM bde2020/spark-worker:${SPARK_IMAGE_TAG}

# Install Python 3 runtime and packages required for MLlib and PostGIS batch writers
RUN apk add --no-cache python3=~3.7 py3-pip \
 && python3 -m pip install --no-cache-dir numpy pg8000

# Enforce Python 3 for PySpark driver and executor processes
ENV PYSPARK_PYTHON=python3
ENV PYSPARK_DRIVER_PYTHON=python3
